version: '3'
services:
  bcb:
    image: "public.ecr.aws/d8b2x5c9/orange-stack-sat-bcb-pix"
    ports:
      - 8082:8082
  erp-itau:
    image: "public.ecr.aws/d8b2x5c9/orange-stack-sat-itau-erp"
    ports:
      - 9091:9091

  mysql_db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: keymanager_db
    volumes:
      - mysql-volume:/var/lib/mysql

volumes:
  mysql-volume: