# Default values for keymanager-grpc.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

deployment:
  name: keymanager-grpc-deployment

horizontalPodAutoscaler:
  name: keymanager-grpc-hpa

configMap:
  name: keymanager-grpc-configmap

secret:
  name: keymanager-grpc-secrets

image:
  repository: mickael32/keymanager-grpc
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

labels:
  app: keymanager-grpc

container:
  port: 50051

# Pegar os valores das variáveis de ambiente na aws
# senha em base64 Q1pubjdDNnZkcHRDbXN3TGpnZ2o=
# senha CZnn7C6vdptCmswLjggj
application:
  DB_URI: jdbc:mysql://keymanager-grpc-db-mickael.cvkl7pbhtcev.us-east-1.rds.amazonaws.com:3306/keymanager
  DB_USER: admin
  DB_PASSWORD: CZnn7C6vdptCmswLjggj
  DB_DIALECT: MYSQL
  ITAU_URL: internal-ac473dd79dd3d45438f40d619c4e7ea9-2067615937.us-east-1.elb.amazonaws.com
  BCB_URL: internal-abcd1dc883b944d5f8b43cd6aad7ec1d-240028978.us-east-1.elb.amazonaws.com

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: "keymanager-grpc-service-account"

podAnnotations: {}

service:
  name: keymanager-grpc-service
  type: ClusterIP
  port: 50051

  hosts:
    - host: chart-example.local
      paths:
      - path: /
        backend:
          serviceName: chart-example.local
          servicePort: 50051
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
