micronaut:
  application:
    name: keymanagerGrpc

grpc:
  server:
    port: ${SERVER_PORT:50051}
    keep-alive-time: 1h
    max-inbound-message-size: 1024

datasources:
  default:
    url: ${DATASOURCE_URL:jdbc:mysql://localhost:3306/keymanager_db}
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${DATASOURCE_USERNAME:root}
    password: ${DATASOURCE_PASSWORD:admin}
    schema-generate: CREATE_DROP
    dialect: MYSQL
jpa.default.properties.hibernate.hbm2ddl.auto: update

itau:
  contas:
    url: ${ITAU_CONTAS_URL:'http://localhost:9091'}

bcb:
  pix:
    url: ${BCB_PIX_URL:'http://localhost:8082'}